version: '3'
services:
  api:
    image: ksc-api
    container_name: ksc-api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8080:5000
    volumes:
      - ./data/keras-cache:/root/.keras
      - ./data/upload:/upload
      - ./data/custom-dataset:/custom-dataset

  webapp:
    image: ksc-app
    container_name: ksc-app
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 80:80
